### ISSUE TITLE
v3.3.0 is throwing an error

### ISSUE THREAD

**Issue by mfts** [resend/resend-node#381]
I saw that `v3.3.0` was made available through npm even though there are no release notes here on GitHub. 

It broke my email sending capability with `next@14.2.4`. 

here's the error which goes back to `@react-email/render@0.0.15` bumped from the prev v0.0.12 

```sh
Error: Dynamic require of "stream" is not supported
    at file:///Users/mfts/dev/mfts/papermark-main/node_modules/@react-email/render/dist/index.mjs:22:9
    at file:///Users/mfts/dev/mfts/papermark-main/node_modules/@react-email/render/dist/index.mjs:104:26
    at Generator.next (<anonymous>)
    at file:///Users/mfts/dev/mfts/papermark-main/node_modules/@react-email/render/dist/index.mjs:41:61
    at new Promise (<anonymous>)
    at __async (file:///Users/mfts/dev/mfts/papermark-main/node_modules/@react-email/render/dist/index.mjs:25:10)
    at readStream (file:///Users/mfts/dev/mfts/papermark-main/node_modules/@react-email/render/dist/index.mjs:94:30)
    at file:///Users/mfts/dev/mfts/papermark-main/node_modules/@react-email/render/dist/index.mjs:133:26
    at Generator.next (<anonymous>)
    at file:///Users/mfts/dev/mfts/papermark-main/node_modules/@react-email/render/dist/index.mjs:41:61
    at new Promise (<anonymous>)
    at __async (file:///Users/mfts/dev/mfts/papermark-main/node_modules/@react-email/render/dist/index.mjs:25:10)
    at onAllReady (file:///Users/mfts/dev/mfts/papermark-main/node_modules/@react-email/render/dist/index.mjs:132:18)
    at finishedTask (/Users/mfts/dev/mfts/papermark-main/node_modules/react-dom/cjs/react-dom-server.node.development.js:6579:5)
    at retryTask (/Users/mfts/dev/mfts/papermark-main/node_modules/react-dom/cjs/react-dom-server.node.development.js:6609:5)
```

**Comment by vasco3** [comment]
I'm also geetting an error when upgrading from v3.2 to 3.3

```
sending email from convex.dev with resend.com and react-email, i upgraded to latest version and now it throwing this error "Uncaught TypeError: reactDOMServer.renderToPipeableStream is not a function
    at __spreadValues11.selectors (../../../node_modules/.pnpm/@react-email+render@0.0.15/node_modules/@react-email/render/dist/index.mjs:130:21)
    at new Promise (<anonymous>)
    at <anonymous> (../../../node_modules/.pnpm/@react-email+render@0.0.15/node_modules/@react-email/render/dist/index.mjs:129:6)
    at next [as next] (<anonymous>)
    at fulfilled (../../../node_modules/.pnpm/@react-email+render@0.0.15/node_modules/@react-email/render/dist/index.mjs:28:8)"
```

**Comment by xixixao** [comment]
What @vasco3 is reporting was broken by https://github.com/resend/react-email/pull/1117 cc @gabrielmfern , specifically the change in `packages/render/src/render-async.ts` from:

```
const reactDOMServer = (await import("react-dom/server")).default;
```
to
```
const reactDOMServer = await import("react-dom/server");
const renderToStream = Object.hasOwn(reactDOMServer, "renderToReadableStream")
```

When I test this in our environment, `"react-dom/server"` has only the default export, which has all the methods. Hence `@react-email/render@0.0.15` is broken for us (Convex runs our own runtime wrapping V8), and potentially for others, and so is `resend@3.3.0`.

The Convex runtime matches the `browser` condition, so I expect others matching the condition to be broken too.

**Comment by gabrielmfern** [comment]
This is because of the issue mentioned in https://github.com/resend/react-email/issues/1486 which has been fixed on React Email's canary, so a workaround should be adding an override for it, like:

```json
  "overrides": {
    "resend": {
      "@react-email/render": "0.0.16-canary.0"
    }
  },
```

**Comment by isMattCoding** [comment]
I'm using yarn, and the `overrides` section in the package.json wasn't overriding the dependency.
I figured out I could use:

```
"resolutions": {
    "resend/@react-email/render": "0.0.16-canary.0"
  },
```

**Comment by mfts** [comment]
> This is because of the issue mentioned in resend/react-email#1486 which has been fixed on React Email's canary, so a workaround should be adding an override for it, like what was mentioned in resend/react-email#1486 (comment)

Thanks @gabrielmfern I understand that the packages are related. But it's pretty bad DX when I upgrade resend to 3.3.0 and it breaks and there's no mention of this workaround or possibility of breaking in the resend changelog. 

Great that there's a workaround but maybe it should be part of a patch update to resend. 

---

Also I just noticed that 3.3.0 wasn't even officially released on github (weird?). ![image](https://github.com/resend/resend-node/assets/4049052/ddfbe118-0028-442d-846c-f4e5f0c595d0)

**Comment by isMattCoding** [comment]
Since [@react-email/render@0.0.16](https://github.com/resend/react-email/releases/tag/%40react-email%2Frender%400.0.16) has been released, this should be resolved as soon as https://github.com/resend/resend-node/pull/395 is merged and released

**Comment by RodrigoVila** [comment]
> Since [@react-email/render@0.0.16](https://github.com/resend/react-email/releases/tag/%40react-email%2Frender%400.0.16) has been released, this should be resolved as soon as #395 is merged and released

Any update on this? have the same problem and the workarounds don't work for me :(. I see PR [#395](https://github.com/resend/resend-node/pull/395) is merged but I think it's not released yet.

Thanks!!

**Comment by acrefoot** [comment]
@vcapretz I see this issue with

- @react-email/render @ 1.1.2(react-dom@19.1.0(react@19.1.0))(react@19.1.0)
- resend @ 4.5.1
- convex backend doing the sending

Looks like all the convex templates including Resend use 3.2.0 or earlier:
https://www.convex.dev/templates?tags=Resend

Looks like the last advice in the discord mentions that 3.3.0 and 3.4.0 are broken, so stick with 3.2.0: https://discord.com/channels/1019350475847499849/1260703577081385050/1260741840559145042

What's the root cause here? I believe that I'm on the latest react-email/render + resend.
